FROM ubuntu:latest
RUN apt-get update -y
RUN apt_get install -y python3-pip python3.11-dev
COPY ./requirements.txt /app/requirements.txt
COPY . /app
WORKDIR /app
RUN pip install -r /app/requirements.txt
ENTRYPOINT [ "python3" ]
CMD ["app.py"]